# Logging settings
logging:
  level:
    root: INFO

spring:
# Thymeleaf settings
  thymeleaf:
    enabled: true
    cache: false

# DB settings
  datasource:
    # For in memory
#    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    # For entity
    url: jdbc:h2:./.data/h2/db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
    sql-script-encoding: UTF-8

    h2.console.enabled: true

doma:
  dialect: h2
